# Generated by Django 2.0.5 on 2018-07-03 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.IntegerField(default=0)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cuadrilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=100)),
                ('vehiculo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EmpleadoCuadrilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.IntegerField(default=0)),
                ('cuil', models.IntegerField(default=0)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('empleado_desde', models.DateTimeField(verbose_name='empleado desde')),
                ('fecha_nac', models.DateTimeField(verbose_name='fecha de nacimiento')),
                ('es_jefe', models.BooleanField(default=False, verbose_name='es jefe de cuadrilla')),
                ('cuadrilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.Cuadrilla')),
            ],
        ),
        migrations.CreateModel(
            name='ParteTrabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('descripcion', models.CharField(max_length=200)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.EmpleadoCuadrilla')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solcitud', models.DateTimeField(verbose_name='fecha de solicitud')),
                ('fecha_inicio', models.DateTimeField(verbose_name='fecha de inicio')),
                ('fecha_fin', models.DateTimeField(verbose_name='fecha de fin')),
                ('descripcion', models.CharField(max_length=500)),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('C', 'En curso'), ('F', 'Finalizado')], max_length=1)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('C', 'En curso'), ('F', 'Finalizado')], max_length=1)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.Servicio')),
            ],
        ),
        migrations.AddField(
            model_name='partetrabajo',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.Tarea'),
        ),
    ]
