# Generated by Django 2.0.5 on 2018-07-05 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpleadoDeCuadrilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.IntegerField(default=0)),
                ('cuil', models.CharField(max_length=13)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('empleado_desde', models.DateField(verbose_name='empleado desde')),
                ('fecha_nac', models.DateField(verbose_name='fecha de nacimiento')),
                ('es_jefe', models.BooleanField(default=False, verbose_name='es jefe de cuadrilla')),
                ('cuadrilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.Cuadrilla')),
            ],
        ),
        migrations.CreateModel(
            name='ParteDeTrabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=200)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.EmpleadoDeCuadrilla')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.Tarea')),
            ],
        ),
        migrations.RemoveField(
            model_name='empleadocuadrilla',
            name='cuadrilla',
        ),
        migrations.RemoveField(
            model_name='partetrabajo',
            name='aprobado_por',
        ),
        migrations.RemoveField(
            model_name='partetrabajo',
            name='tarea',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fecha_fin',
            field=models.DateField(verbose_name='fecha de fin'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fecha_inicio',
            field=models.DateField(verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fecha_solcitud',
            field=models.DateField(verbose_name='fecha de solicitud'),
        ),
        migrations.DeleteModel(
            name='EmpleadoCuadrilla',
        ),
        migrations.DeleteModel(
            name='ParteTrabajo',
        ),
    ]
