# Generated by Django 2.2.1 on 2019-06-14 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_remove_empleadodecuadrilla_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partedetrabajo',
            name='aprobado_por',
        ),
    ]
