# Generated by Django 2.0.5 on 2019-05-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_auto_20190515_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En curso', 'En curso'), ('Finalizado', 'Finalizado')], max_length=12),
        ),
    ]
