# Generated by Django 2.0.5 on 2019-05-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_auto_20190515_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de fin'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de inicio'),
        ),
    ]
