# Generated by Django 2.2.1 on 2019-06-14 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicios', '0004_remove_partedetrabajo_aprobado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='partedetrabajo',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.User'),
        ),
    ]
