# Generated by Django 2.2.1 on 2019-06-02 00:19

from django.db import migrations


def apply_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.bulk_create([
        Group(name=u'jefecuadrilla'),
        Group(name=u'administracion'),
        Group(name=u'coordinador'),
    ])


def revert_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(
        name__in=[
            u'jefecuadrilla',
            u'administracion',
            u'coordinador',
        ]
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('servicios', '0005_auto_20190531_1108'),
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration)
    ]
