# Generated by Django 2.2.1 on 2019-06-02 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_auto_20190601_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='cuadrilla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.Cuadrilla'),
        ),
    ]
